---

lo_address: 10.0.0.2/32

router_id: 10.0.0.2

ospf_networks:
  - subnet: "10.0.0.2/32"
  - subnet: "10.1.2.0/30"
  - subnet: "10.2.2.0/30"
  - subnet: "10.0.20.0/30"
  - subnet: "10.0.21.0/30"

interfaces:
  - name: "enp0s8"
    address: "10.1.2.1/30"
    connected_to: "spine01"
  - name: "enp0s9"
    address: "10.2.2.1/30"
    connected_to: "spine02"
  - name: "enp0s10"
    address: "10.0.20.1/30"
    connected_to: "vm02"
  - name: "enp0s16"
    address: "10.0.21.1/30"
    connected_to: "vm02"